import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import { Footer } from '../components/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Atilho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Atilho</h1>
        <section>
          <h2>Mês Atual</h2>
          <dl>
            <dt>Receitas</dt>
            <dd>R$ 1.2312,32</dd>
            <dt>Depesas</dt>
            <dd>R$ 982,8988</dd>
          </dl>
        </section>

        <section>
          <h2>Últimas Transações</h2>
          <table>
            <thead>
              <tr>
                <th>Tipo</th>
                <th>Descrição</th>
                <th>Data</th>
                <th>Valor</th>
                <th>Conta</th>
                <th>Tags</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>receita</td>
                <td>supermercado</td>
                <td>16 Ago 2022</td>
                <td>R$ 123,45</td>
                <td>alelo alimentação</td>
                <td>zaffari wallig domingo</td>
              </tr>
              <tr>
                <td>receita</td>
                <td>supermercado</td>
                <td>16 Ago 2022</td>
                <td>R$ 123,45</td>
                <td>alelo alimentação</td>
                <td>zaffari wallig domingo</td>
              </tr>
              <tr>
                <td>receita</td>
                <td>supermercado</td>
                <td>16 Ago 2022</td>
                <td>R$ 123,45</td>
                <td>alelo alimentação</td>
                <td>zaffari wallig domingo</td>
              </tr>
            </tbody>
          </table>
        </section>
      </main>
      <Footer />
    </div>
  );
}
